### ISSUE TITLE
2017.ttl is actually html

### ISSUE THREAD

**Issue by smrgeoinfo** [CGI-IUGS/timescale-data#4]
https://raw.githubusercontent.com/CGI-IUGS/timescale-data/master/rdf/isc2017.ttl

**Comment by dr-shorthair** [comment]
Something Ollie managed to do over at https://github.com/GeoscienceAustralia/geosciml.org/commits/master/resource/static/vocabulary/timescale/isc2017.ttl on 2019-06-04 before the repo was moved over to this new location. 

Now re-instated as TTL and RDF/XML
