### ISSUE TITLE
GSSP records not updated in the ttl files

### ISSUE THREAD

**Issue by xgmachina** [CGI-IUGS/timescale-data#5]
I took a look of the ISC2018 and ISC 2020 versions of the ttl files. Seems some golden spike information is missing. 

In 2018-08 version of the ISC chart, there are 72 golden spikes. In the corresponding ttl file I can find 64. 

In the 2020 version of the ISC chart there are 74 golden spikes. In the corresponding ttl file I can find 66.  

Also in some place the golden spike attributes are incorrect. Such as geo:hasGeometry isc:BaseMiddleOrdovician-location in the below:
```
isc:BaseMeghalayanSP
  a gts:StratigraphicPoint ;
  dct:source "International Commission on Stratigraphy - Formal subdivision of the Holocene Series/Epoch"@en ;
  gts:ratifiedGSSP true ;
  gts:status "Ratified 2018-06-26"@en ;
  geo:hasGeometry isc:BaseMiddleOrdovician-location ;
  rdfs:comment "Mawmluh Cave speleothem, Meghalaya, India."@en ;
  rdfs:label "Stratotype Point Base of Meghalayan"@en ;
  rdfs:seeAlso <http://stratigraphy.org/index.php/ics-news-and-meetings/125-formal-subdivision-of-the-holocene-series-epoch> ;
  rdfs:seeAlso <http://www.stratigraphy.org/GSSP/index.html> ;
  skos:prefLabel "Stratotype Point Base of Meghalayan"@en ;
.
```

And  time:numericPosition "4200"^^xsd:decimal in the below:

```
isc:BaseMeghalayanTime
  a time:TimePosition ;
  time:hasTRS <http://resource.geosciml.org/classifier/cgi/geologicage/bp> ;
  time:numericPosition "4200"^^xsd:decimal ;
```

**Comment by xgmachina** [comment]
The gssp information here https://timescalefoundation.org/gssp/index.php?parentid=all seems to be more updated than here https://stratigraphy.org/gssp/

**Comment by arademaker** [comment]
The second link is broken. I am assuming you mean https://stratigraphy.org/gssps/? 

Thank you for the first link. We definitely need to sync the two sources to make this repository a reference for the linked data model of these informations
